"""TranslateGemma utility functions for language resolution and prompt formatting.

This module maps language names and codes to the canonical forms expected by TranslateGemma,
and constructs user prompts adhering to the TranslateGemma prompt guide.
"""

from __future__ import annotations
import re

# Comprehensive mapping of lowercase language codes to their canonical names
# as supported by TranslateGemma (built on Gemma 3).
CODE_TO_NAME: dict[str, str] = {
    "aa": "Afar",
    "aa-dj": "Afar",
    "aa-er": "Afar",
    "ab": "Abkhazian",
    "af": "Afrikaans",
    "af-na": "Afrikaans",
    "ak": "Akan",
    "am": "Amharic",
    "an": "Aragonese",
    "ar": "Arabic",
    "ar-ae": "Arabic",
    "ar-bh": "Arabic",
    "ar-dj": "Arabic",
    "ar-dz": "Arabic",
    "ar-eg": "Arabic",
    "ar-eh": "Arabic",
    "ar-er": "Arabic",
    "ar-il": "Arabic",
    "ar-iq": "Arabic",
    "ar-jo": "Arabic",
    "ar-km": "Arabic",
    "ar-kw": "Arabic",
    "ar-lb": "Arabic",
    "ar-ly": "Arabic",
    "ar-ma": "Arabic",
    "ar-mr": "Arabic",
    "ar-om": "Arabic",
    "ar-ps": "Arabic",
    "ar-qa": "Arabic",
    "ar-sa": "Arabic",
    "ar-sd": "Arabic",
    "ar-so": "Arabic",
    "ar-ss": "Arabic",
    "ar-sy": "Arabic",
    "ar-td": "Arabic",
    "ar-tn": "Arabic",
    "ar-ye": "Arabic",
    "as": "Assamese",
    "az": "Azerbaijani",
    "az-arab": "Azerbaijani",
    "az-arab-iq": "Azerbaijani",
    "az-arab-tr": "Azerbaijani",
    "az-cyrl": "Azerbaijani",
    "az-latn": "Azerbaijani",
    "ba": "Bashkir",
    "be": "Belarusian",
    "be-tarask": "Belarusian",
    "bg": "Bulgarian",
    "bg-bg": "Bulgarian",
    "bm": "Bambara",
    "bm-nkoo": "Bambara",
    "bn": "Bengali",
    "bn-in": "Bengali",
    "bo": "Tibetan",
    "bo-in": "Tibetan",
    "br": "Breton",
    "bs": "Bosnian",
    "bs-cyrl": "Bosnian",
    "bs-latn": "Bosnian",
    "ca": "Catalan",
    "ca-ad": "Catalan",
    "ca-es": "Catalan",
    "ca-fr": "Catalan",
    "ca-it": "Catalan",
    "ce": "Chechen",
    "co": "Corsican",
    "cs": "Czech",
    "cs-cz": "Czech",
    "cv": "Chuvash",
    "cy": "Welsh",
    "da": "Danish",
    "da-dk": "Danish",
    "da-gl": "Danish",
    "de": "German",
    "de-at": "German",
    "de-be": "German",
    "de-ch": "German",
    "de-de": "German",
    "de-it": "German",
    "de-li": "German",
    "de-lu": "German",
    "dv": "Divehi",
    "dz": "Dzongkha",
    "ee": "Ewe",
    "ee-tg": "Ewe",
    "el": "Greek",
    "el-cy": "Greek",
    "el-gr": "Greek",
    "el-polyton": "Greek",
    "en": "English",
    "en-ae": "English",
    "en-ag": "English",
    "en-ai": "English",
    "en-as": "English",
    "en-at": "English",
    "en-au": "English",
    "en-bb": "English",
    "en-be": "English",
    "en-bi": "English",
    "en-bm": "English",
    "en-bs": "English",
    "en-bw": "English",
    "en-bz": "English",
    "en-ca": "English",
    "en-cc": "English",
    "en-ch": "English",
    "en-ck": "English",
    "en-cm": "English",
    "en-cx": "English",
    "en-cy": "English",
    "en-cz": "English",
    "en-de": "English",
    "en-dg": "English",
    "en-dk": "English",
    "en-dm": "English",
    "en-er": "English",
    "en-es": "English",
    "en-fi": "English",
    "en-fj": "English",
    "en-fk": "English",
    "en-fm": "English",
    "en-fr": "English",
    "en-gb": "English",
    "en-gd": "English",
    "en-gg": "English",
    "en-gh": "English",
    "en-gi": "English",
    "en-gm": "English",
    "en-gs": "English",
    "en-gu": "English",
    "en-gy": "English",
    "en-hk": "English",
    "en-hu": "English",
    "en-id": "English",
    "en-ie": "English",
    "en-il": "English",
    "en-im": "English",
    "en-in": "English",
    "en-io": "English",
    "en-it": "English",
    "en-je": "English",
    "en-jm": "English",
    "en-ke": "English",
    "en-ki": "English",
    "en-kn": "English",
    "en-ky": "English",
    "en-lc": "English",
    "en-lr": "English",
    "en-ls": "English",
    "en-mg": "English",
    "en-mh": "English",
    "en-mo": "English",
    "en-mp": "English",
    "en-ms": "English",
    "en-mt": "English",
    "en-mu": "English",
    "en-mv": "English",
    "en-mw": "English",
    "en-my": "English",
    "en-na": "English",
    "en-nf": "English",
    "en-ng": "English",
    "en-nl": "English",
    "en-no": "English",
    "en-nr": "English",
    "en-nu": "English",
    "en-nz": "English",
    "en-pg": "English",
    "en-ph": "English",
    "en-pk": "English",
    "en-pl": "English",
    "en-pn": "English",
    "en-pr": "English",
    "en-pt": "English",
    "en-pw": "English",
    "en-ro": "English",
    "en-rw": "English",
    "en-sb": "English",
    "en-sc": "English",
    "en-sd": "English",
    "en-se": "English",
    "en-sg": "English",
    "en-sh": "English",
    "en-si": "English",
    "en-sk": "English",
    "en-sl": "English",
    "en-ss": "English",
    "en-sx": "English",
    "en-sz": "English",
    "en-tc": "English",
    "en-tk": "English",
    "en-to": "English",
    "en-tt": "English",
    "en-tv": "English",
    "en-tz": "English",
    "en-ug": "English",
    "en-um": "English",
    "en-vc": "English",
    "en-vg": "English",
    "en-vi": "English",
    "en-vu": "English",
    "en-ws": "English",
    "en-za": "English",
    "en-zm": "English",
    "en-zw": "English",
    "eo": "Esperanto",
    "es": "Spanish",
    "es-ar": "Spanish",
    "es-bo": "Spanish",
    "es-br": "Spanish",
    "es-bz": "Spanish",
    "es-cl": "Spanish",
    "es-co": "Spanish",
    "es-cr": "Spanish",
    "es-cu": "Spanish",
    "es-do": "Spanish",
    "es-ea": "Spanish",
    "es-ec": "Spanish",
    "es-es": "Spanish",
    "es-gq": "Spanish",
    "es-gt": "Spanish",
    "es-hn": "Spanish",
    "es-ic": "Spanish",
    "es-mx": "Spanish",
    "es-ni": "Spanish",
    "es-pa": "Spanish",
    "es-pe": "Spanish",
    "es-ph": "Spanish",
    "es-pr": "Spanish",
    "es-py": "Spanish",
    "es-sv": "Spanish",
    "es-us": "Spanish",
    "es-uy": "Spanish",
    "es-ve": "Spanish",
    "et": "Estonian",
    "et-ee": "Estonian",
    "eu": "Basque",
    "fa": "Persian",
    "fa-af": "Persian",
    "fa-ir": "Persian",
    "ff": "Fulah",
    "ff-adlm": "Fulah",
    "ff-adlm-bf": "Fulah",
    "ff-adlm-cm": "Fulah",
    "ff-adlm-gh": "Fulah",
    "ff-adlm-gm": "Fulah",
    "ff-adlm-gw": "Fulah",
    "ff-adlm-lr": "Fulah",
    "ff-adlm-mr": "Fulah",
    "ff-adlm-ne": "Fulah",
    "ff-adlm-ng": "Fulah",
    "ff-adlm-sl": "Fulah",
    "ff-adlm-sn": "Fulah",
    "ff-latn": "Fulah",
    "ff-latn-bf": "Fulah",
    "ff-latn-cm": "Fulah",
    "ff-latn-gh": "Fulah",
    "ff-latn-gm": "Fulah",
    "ff-latn-gn": "Fulah",
    "ff-latn-gw": "Fulah",
    "ff-latn-lr": "Fulah",
    "ff-latn-mr": "Fulah",
    "ff-latn-ne": "Fulah",
    "ff-latn-ng": "Fulah",
    "ff-latn-sl": "Fulah",
    "fi": "Finnish",
    "fi-fi": "Finnish",
    "fil-ph": "Filipino",
    "fo": "Faroese",
    "fo-dk": "Faroese",
    "fr": "French",
    "fr-be": "French",
    "fr-bf": "French",
    "fr-bi": "French",
    "fr-bj": "French",
    "fr-bl": "French",
    "fr-ca": "French",
    "fr-cd": "French",
    "fr-cf": "French",
    "fr-cg": "French",
    "fr-ch": "French",
    "fr-ci": "French",
    "fr-cm": "French",
    "fr-dj": "French",
    "fr-dz": "French",
    "fr-fr": "French",
    "fr-ga": "French",
    "fr-gf": "French",
    "fr-gn": "French",
    "fr-gp": "French",
    "fr-gq": "French",
    "fr-ht": "French",
    "fr-km": "French",
    "fr-lu": "French",
    "fr-ma": "French",
    "fr-mc": "French",
    "fr-mf": "French",
    "fr-mg": "French",
    "fr-ml": "French",
    "fr-mq": "French",
    "fr-mr": "French",
    "fr-mu": "French",
    "fr-nc": "French",
    "fr-ne": "French",
    "fr-pf": "French",
    "fr-pm": "French",
    "fr-re": "French",
    "fr-rw": "French",
    "fr-sc": "French",
    "fr-sn": "French",
    "fr-sy": "French",
    "fr-td": "French",
    "fr-tg": "French",
    "fr-tn": "French",
    "fr-vu": "French",
    "fr-wf": "French",
    "fr-yt": "French",
    "fy": "Western Frisian",
    "ga": "Irish",
    "ga-gb": "Irish",
    "gd": "Scottish Gaelic",
    "gl": "Galician",
    "gn": "Guarani",
    "gu": "Gujarati",
    "gu-in": "Gujarati",
    "gv": "Manx",
    "ha": "Hausa",
    "ha-arab": "Hausa",
    "ha-arab-sd": "Hausa",
    "ha-gh": "Hausa",
    "ha-ne": "Hausa",
    "he": "Hebrew",
    "he-il": "Hebrew",
    "hi": "Hindi",
    "hi-in": "Hindi",
    "hi-latn": "Hindi",
    "hr": "Croatian",
    "hr-ba": "Croatian",
    "hr-hr": "Croatian",
    "ht": "Haitian",
    "hu": "Hungarian",
    "hu-hu": "Hungarian",
    "hy": "Armenian",
    "ia": "Interlingua",
    "id": "Indonesian",
    "id-id": "Indonesian",
    "ie": "Interlingue",
    "ig": "Igbo",
    "ii": "Sichuan Yi",
    "ik": "Inupiaq",
    "io": "Ido",
    "is": "Icelandic",
    "it": "Italian",
    "it-ch": "Italian",
    "it-it": "Italian",
    "it-sm": "Italian",
    "it-va": "Italian",
    "iu": "Inuktitut",
    "iu-latn": "Inuktitut",
    "ja": "Japanese",
    "ja-jp": "Japanese",
    "jv": "Javanese",
    "ka": "Georgian",
    "ki": "Kikuyu",
    "kk": "Kazakh",
    "kk-arab": "Kazakh",
    "kk-cyrl": "Kazakh",
    "kk-kz": "Kazakh",
    "kl": "Kalaallisut",
    "km": "Central Khmer",
    "kn": "Kannada",
    "kn-in": "Kannada",
    "ko": "Korean",
    "ko-cn": "Korean",
    "ko-kp": "Korean",
    "ko-kr": "Korean",
    "ks": "Kashmiri",
    "ks-arab": "Kashmiri",
    "ks-deva": "Kashmiri",
    "ku": "Kurdish",
    "kw": "Cornish",
    "ky": "Kyrgyz",
    "la": "Latin",
    "lb": "Luxembourgish",
    "lg": "Ganda",
    "ln": "Lingala",
    "ln-ao": "Lingala",
    "ln-cf": "Lingala",
    "ln-cg": "Lingala",
    "lo": "Lao",
    "lt": "Lithuanian",
    "lt-lt": "Lithuanian",
    "lu": "Luba-Katanga",
    "lv": "Latvian",
    "lv-lv": "Latvian",
    "mg": "Malagasy",
    "mi": "Maori",
    "mk": "Macedonian",
    "ml": "Malayalam",
    "ml-in": "Malayalam",
    "mn": "Mongolian",
    "mn-mong": "Mongolian",
    "mn-mong-mn": "Mongolian",
    "mr": "Marathi",
    "mr-in": "Marathi",
    "ms": "Malay",
    "ms-arab": "Malay",
    "ms-arab-bn": "Malay",
    "ms-bn": "Malay",
    "ms-id": "Malay",
    "ms-sg": "Malay",
    "mt": "Maltese",
    "my": "Burmese",
    "nb": "Norwegian Bokmål",
    "nb-sj": "Norwegian Bokmål",
    "nd": "North Ndebele",
    "ne": "Nepali",
    "ne-in": "Nepali",
    "nl": "Dutch",
    "nl-aw": "Dutch",
    "nl-be": "Dutch",
    "nl-bq": "Dutch",
    "nl-cw": "Dutch",
    "nl-nl": "Dutch",
    "nl-sr": "Dutch",
    "nl-sx": "Dutch",
    "nn": "Norwegian Nynorsk",
    "no": "Norwegian",
    "no-no": "Norwegian",
    "nr": "South Ndebele",
    "nv": "Navajo",
    "ny": "Chichewa",
    "oc": "Occitan",
    "oc-es": "Occitan",
    "om": "Oromo",
    "om-ke": "Oromo",
    "or": "Oriya",
    "os": "Ossetian",
    "os-ru": "Ossetian",
    "pa": "Punjabi",
    "pa-in": "Punjabi",
    "pa-arab": "Punjabi",
    "pa-guru": "Punjabi",
    "pl": "Polish",
    "pl-pl": "Polish",
    "ps": "Pashto",
    "ps-pk": "Pashto",
    "pt": "Portuguese",
    "pt-ao": "Portuguese",
    "pt-br": "Portuguese",
    "pt-ch": "Portuguese",
    "pt-cv": "Portuguese",
    "pt-gq": "Portuguese",
    "pt-gw": "Portuguese",
    "pt-lu": "Portuguese",
    "pt-mo": "Portuguese",
    "pt-mz": "Portuguese",
    "pt-pt": "Portuguese",
    "pt-st": "Portuguese",
    "pt-tl": "Portuguese",
    "qu": "Quechua",
    "qu-bo": "Quechua",
    "qu-ec": "Quechua",
    "rm": "Romansh",
    "rn": "Rundi",
    "ro": "Romanian",
    "ro-md": "Romanian",
    "ro-ro": "Romanian",
    "ru": "Russian",
    "ru-by": "Russian",
    "ru-kg": "Russian",
    "ru-kz": "Russian",
    "ru-md": "Russian",
    "ru-ru": "Russian",
    "ru-ua": "Russian",
    "rw": "Kinyarwanda",
    "sa": "Sanskrit",
    "sc": "Sardinian",
    "sd": "Sindhi",
    "sd-arab": "Sindhi",
    "sd-deva": "Sindhi",
    "se": "Northern Sami",
    "se-fi": "Northern Sami",
    "se-se": "Northern Sami",
    "sg": "Sango",
    "si": "Sinhala",
    "sk": "Slovak",
    "sk-sk": "Slovak",
    "sl": "Slovenian",
    "sl-si": "Slovenian",
    "sn": "Shona",
    "so": "Somali",
    "so-dj": "Somali",
    "so-et": "Somali",
    "so-ke": "Somali",
    "sq": "Albanian",
    "sq-mk": "Albanian",
    "sq-xk": "Albanian",
    "sr": "Serbian",
    "sr-rs": "Serbian",
    "sr-cyrl": "Serbian",
    "sr-cyrl-ba": "Serbian",
    "sr-cyrl-me": "Serbian",
    "sr-cyrl-xk": "Serbian",
    "sr-latn": "Serbian",
    "sr-latn-ba": "Serbian",
    "sr-latn-me": "Serbian",
    "sr-latn-xk": "Serbian",
    "ss": "Swati",
    "ss-sz": "Swati",
    "st": "Southern Sotho",
    "st-ls": "Southern Sotho",
    "su": "Sundanese",
    "su-latn": "Sundanese",
    "sv": "Swedish",
    "sv-ax": "Swedish",
    "sv-fi": "Swedish",
    "sv-se": "Swedish",
    "sw": "Swahili",
    "sw-cd": "Swahili",
    "sw-ke": "Swahili",
    "sw-tz": "Swahili",
    "sw-ug": "Swahili",
    "ta": "Tamil",
    "ta-in": "Tamil",
    "ta-lk": "Tamil",
    "ta-my": "Tamil",
    "ta-sg": "Tamil",
    "te": "Telugu",
    "te-in": "Telugu",
    "tg": "Tajik",
    "th": "Thai",
    "th-th": "Thai",
    "ti": "Tigrinya",
    "ti-er": "Tigrinya",
    "tk": "Turkmen",
    "tl": "Tagalog",
    "tn": "Tswana",
    "tn-bw": "Tswana",
    "to": "Tonga",
    "tr": "Turkish",
    "tr-cy": "Turkish",
    "tr-tr": "Turkish",
    "ts": "Tsonga",
    "tt": "Tatar",
    "ug": "Uyghur",
    "uk": "Ukrainian",
    "uk-ua": "Ukrainian",
    "ur": "Urdu",
    "ur-in": "Urdu",
    "ur-pk": "Urdu",
    "uz": "Uzbek",
    "uz-arab": "Uzbek",
    "uz-cyrl": "Uzbek",
    "uz-latn": "Uzbek",
    "ve": "Venda",
    "vi": "Vietnamese",
    "vi-vn": "Vietnamese",
    "vo": "Volapük",
    "wa": "Walloon",
    "wo": "Wolof",
    "xh": "Xhosa",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "yo-bj": "Yoruba",
    "za": "Zhuang",
    "zh": "Chinese",
    "zh-ch": "Chinese",
    "zh-tw": "Chinese",
    "zh-hans": "Chinese",
    "zh-hans-hk": "Chinese",
    "zh-hans-mo": "Chinese",
    "zh-hans-my": "Chinese",
    "zh-hans-sg": "Chinese",
    "zh-hant": "Chinese",
    "zh-hant-hk": "Chinese",
    "zh-hant-mo": "Chinese",
    "zh-hant-my": "Chinese",
    "zh-latn": "Chinese",
    "zu": "Zulu",
    "zu-za": "Zulu"
}

# A map of common lowercased language names to their primary language codes
NAME_TO_CODE: dict[str, str] = {
    "afar": "aa",
    "abkhazian": "ab",
    "afrikaans": "af",
    "akan": "ak",
    "amharic": "am",
    "aragonese": "an",
    "arabic": "ar",
    "assamese": "as",
    "azerbaijani": "az",
    "bashkir": "ba",
    "belarusian": "be",
    "bulgarian": "bg",
    "bambara": "bm",
    "bengali": "bn",
    "tibetan": "bo",
    "breton": "br",
    "bosnian": "bs",
    "catalan": "ca",
    "chechen": "ce",
    "corsican": "co",
    "czech": "cs",
    "chuvash": "cv",
    "welsh": "cy",
    "danish": "da",
    "german": "de",
    "divehi": "dv",
    "dzongkha": "dz",
    "ewe": "ee",
    "greek": "el",
    "english": "en",
    "esperanto": "eo",
    "spanish": "es",
    "estonian": "et",
    "basque": "eu",
    "persian": "fa",
    "fulah": "ff",
    "finnish": "fi",
    "filipino": "fil-ph",
    "faroese": "fo",
    "french": "fr",
    "western frisian": "fy",
    "irish": "ga",
    "scottish gaelic": "gd",
    "galician": "gl",
    "guarani": "gn",
    "gujarati": "gu",
    "manx": "gv",
    "hausa": "ha",
    "hebrew": "he",
    "hindi": "hi",
    "croatian": "hr",
    "haitian": "ht",
    "hungarian": "hu",
    "armenian": "hy",
    "interlingua": "ia",
    "indonesian": "id",
    "interlingue": "ie",
    "igbo": "ig",
    "sichuan yi": "ii",
    "inupiaq": "ik",
    "ido": "io",
    "icelandic": "is",
    "italian": "it",
    "inuktitut": "iu",
    "japanese": "ja",
    "javanese": "jv",
    "georgian": "ka",
    "kikuyu": "ki",
    "kazakh": "kk",
    "kalaallisut": "kl",
    "central khmer": "km",
    "kennada": "kn",
    "kannada": "kn",
    "korean": "ko",
    "kashmiri": "ks",
    "kurdish": "ku",
    "cornish": "kw",
    "kyrgyz": "ky",
    "latin": "la",
    "luxembourgish": "lb",
    "ganda": "lg",
    "lingala": "ln",
    "lao": "lo",
    "lithuanian": "lt",
    "luba-katanga": "lu",
    "latvian": "lv",
    "malagasy": "mg",
    "maori": "mi",
    "macedonian": "mk",
    "malayalam": "ml",
    "mongolian": "mn",
    "marathi": "mr",
    "malay": "ms",
    "maltese": "mt",
    "burmese": "my",
    "norwegian bokmål": "nb",
    "north ndebele": "nd",
    "nepali": "ne",
    "dutch": "nl",
    "norwegian nynorsk": "nn",
    "norwegian": "no",
    "south ndebele": "nr",
    "navajo": "nv",
    "chichewa": "ny",
    "occitan": "oc",
    "oromo": "om",
    "oriya": "or",
    "ossetian": "os",
    "punjabi": "pa",
    "polish": "pl",
    "pashto": "ps",
    "portuguese": "pt",
    "quechua": "qu",
    "romansh": "rm",
    "rundi": "rn",
    "romanian": "ro",
    "russian": "ru",
    "kinyarwanda": "rw",
    "sanskrit": "sa",
    "sardinian": "sc",
    "sindhi": "sd",
    "northern sami": "se",
    "sango": "sg",
    "sinhala": "si",
    "slovak": "sk",
    "slovenian": "sl",
    "shona": "sn",
    "somali": "so",
    "albanian": "sq",
    "serbian": "sr",
    "swati": "ss",
    "southern sotho": "st",
    "sundanese": "su",
    "swedish": "sv",
    "swahili": "sw",
    "tamil": "ta",
    "telugu": "te",
    "tajik": "tg",
    "thai": "th",
    "tigrinya": "ti",
    "turkmen": "tk",
    "tagalog": "tl",
    "tswana": "tn",
    "tonga": "to",
    "turkish": "tr",
    "tsonga": "ts",
    "tatar": "tt",
    "uyghur": "ug",
    "ukrainian": "uk",
    "urdu": "ur",
    "uzbek": "uz",
    "venda": "ve",
    "vietnamese": "vi",
    "volapük": "vo",
    "walloon": "wa",
    "wolof": "wo",
    "xhosa": "xh",
    "yiddish": "yi",
    "yoruba": "yo",
    "zhuang": "za",
    "chinese": "zh",
    "chinese (simplified)": "zh-Hans",
    "chinese (traditional)": "zh-Hant",
    "simplified chinese": "zh-Hans",
    "traditional chinese": "zh-Hant",
    "zulu": "zu"
}


def is_translategemma_model(model_name: str) -> bool:
    """Checks if the given model name is TranslateGemma."""
    return "translategemma" in model_name.lower()


def resolve_translategemma_lang(lang: str) -> tuple[str, str]:
    """Resolves a language name or code into canonical TranslateGemma values.

    Args:
        lang: Language name (e.g. "English", "Vietnamese") or code (e.g. "en", "vi-VN").

    Returns:
        A tuple of (Canonical Name, Canonical Code).
    """
    lang_clean = lang.strip()
    lang_lower = lang_clean.lower()

    # 1. Direct match on code
    if lang_lower in CODE_TO_NAME:
        return CODE_TO_NAME[lang_lower], lang_clean

    # 2. Try looking up names in NAME_TO_CODE
    if lang_lower in NAME_TO_CODE:
        canonical_code = NAME_TO_CODE[lang_lower]
        canonical_name = CODE_TO_NAME.get(canonical_code.lower(), lang_clean.capitalize())
        return canonical_name, canonical_code

    # 3. Check code mapping case-insensitively
    for code, name in CODE_TO_NAME.items():
        if name.lower() == lang_lower:
            return name, code

    # 4. Fallback for sub-codes, e.g., "en-US" -> base "en"
    if "-" in lang_clean:
        base = lang_clean.split("-")[0].lower()
        if base in CODE_TO_NAME:
            return CODE_TO_NAME[base], lang_clean

    # Final fallback: capitalize name, keep code as is
    return lang_clean.capitalize(), lang_clean


def build_translategemma_prompt(
    source_name: str,
    source_code: str,
    target_name: str,
    target_code: str,
    text: str,
    strict: bool = False,
) -> str:
    """Builds the single-user-message TranslateGemma prompt.

    Args:
        source_name: Name of the source language (e.g., "English").
        source_code: Code of the source language (e.g., "en").
        target_name: Name of the target language (e.g., "Vietnamese").
        target_code: Code of the target language (e.g., "vi").
        text: Text blocks to translate.
        strict: If True, appends strict formatting rules to prevent omissions.

    Returns:
        The formatted prompt ready to be sent to the model.
    """
    strict_instruction = ""
    if strict:
        strict_instruction = (
            "\nCRITICAL: You must return exactly the same number of translation blocks as the input. "
            "Do not omit any numbers. Do not add any explanations or notes. "
            "Format each output block starting with the correct index bracket: [index] translation text."
        )

    return (
        f"You are a professional {source_name} ({source_code}) to {target_name} ({target_code}) translator. "
        f"Your goal is to accurately convey the meaning and nuances of the original {source_name} text "
        f"while adhering to {target_name} grammar, vocabulary, and cultural sensitivities.\n"
        f"Produce only the {target_name} translation, without any additional explanations or commentary. "
        f"Please translate the following {source_name} text into {target_name}:{strict_instruction}\n\n\n{text}"
    )
